---
# OS-specific variables for Debian — iSCSI target role

_iscsi_target_packages:
  - targetcli-fb
  - python3-rtslib-fb

_iscsi_target_service: rtslib-fb-targetctl
_iscsi_saveconfig_path: /etc/rtslib-fb-target/saveconfig.json
