---
- name: restart networkd
  ansible.builtin.systemd:
    name: systemd-networkd
    state: restarted
  when: networking_restart_on_change | default(false)

- name: reload network sysctl
  ansible.builtin.command:
    cmd: sysctl --system
