---
# OS-specific variables for Debian — services role

_nfs_packages:
  - nfs-kernel-server
  - nfs-common

_nfs_server_service: nfs-kernel-server

_samba_packages:
  - samba
  - samba-common

_samba_services:
  - smbd
  - nmbd

_iscsi_client_target_packages:
  - targetcli-fb
  - python3-rtslib-fb

_iscsi_target_service: rtslib-fb-targetctl
_iscsi_saveconfig_path: /etc/rtslib-fb-target/saveconfig.json
