---
# =============================================================================
# quorum — Lightweight Quorum Voter
# =============================================================================

mgmt_ip: "10.20.20.3"

ssh_listen_addresses:
  - "{{ mgmt_ip }}"
